language: php

# test against this php versions
php:
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"

before_script:
  - wget https://github.com/contao/core/zipball/master -O contao.zip
  - mkdir contao
  - unzip -x contao.zip -d contao

# run tests from "test" directory
script: phpunit -dinclude_path=".:/usr/share/pear:./contao" test
